const state={rows:[],mode:"live"};
const money=v=>Number.isFinite(v)?`$${v.toFixed(2)}`:"--";
function showPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll("[data-page]").forEach(x=>x.classList.toggle("active",x.dataset.page===id))}
document.querySelectorAll("[data-page]").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.page)));
function renderStatus(status){const badge=document.querySelector(".badge");badge.textContent=`Feeds: ${status.overall.toUpperCase()}${status.generated_at?` · ${status.generated_at}`:" · never refreshed"}`;badge.className=`badge ${status.overall}`;const panel=document.getElementById("sourceStatus");panel.innerHTML=Object.entries(status.sources||{}).map(([name,item])=>`<div class="status-row"><span>${name.toUpperCase()}</span><strong class="${item.state}">${item.state.toUpperCase()} · ${item.row_count||0} rows${item.error?` · ${item.error}`:""}</strong></div>`).join("")}
function merge(market,gas,weather){const gasValue=gas.rows?.[0]?.gas;const weatherByHour=new Map((weather.rows||[]).map(x=>[x.hour.slice(0,13),x]));return (market.rows||[]).map(row=>{const w=weatherByHour.get(row.hour.slice(0,13))||{};return {...row,gas:gasValue,temperature:w.temperature,condition:w.condition,source:"NYISO/EIA/NWS"}}).filter(r=>Number.isFinite(Number(r.lbmp))&&Number.isFinite(Number(r.gas)))}
function render(){const forecast=calculateForecast(state.rows);const body=document.querySelector("#forecastTable tbody");body.innerHTML=forecast.map(r=>`<tr><td>${r.hour}</td><td>${money(r.lbmp)}</td><td>${money(r.gas)}</td><td>${money(r.fuelCost)}</td><td>${money(r.allInCost)}</td><td>${money(r.margin)}</td><td>${r.mw}</td><td>${money(r.grossProfit)}</td><td>${money(r.allocation)}</td><td>${money(r.netProfit)}</td><td>${r.status}</td><td>${r.source}</td></tr>`).join("");document.getElementById("kpiAvgLbmp").textContent=money(forecast.length?forecast.reduce((a,r)=>a+r.lbmp,0)/forecast.length:NaN);document.getElementById("kpiGas").textContent=money(forecast[0]?.gas);document.getElementById("kpiProfitable").textContent=forecast.filter(r=>r.netProfit>0).length;document.getElementById("lastUpdated").textContent=`Mode: ${state.mode}`}
async function startup(){try{const status=await ISSFeeds.status();renderStatus(status);if(status.sources?.nyiso?.state!=="online"||status.sources?.eia?.state!=="online")throw new Error("Required market or fuel feed is offline");const [market,gas,weather]=await Promise.all([ISSFeeds.market(),ISSFeeds.gas(),ISSFeeds.weather()]);state.rows=merge(market,gas,weather);if(!state.rows.length)throw new Error("Live feeds produced zero aligned rows");render()}catch(error){document.getElementById("sourceStatus").insertAdjacentHTML("beforeend",`<div class="status-row"><span>APPLICATION</span><strong class="offline">OFFLINE · ${error.message}</strong></div>`);render()}}
document.getElementById("resetDemo")?.addEventListener("click",()=>{state.rows=window.ISS_DEMO_DATA;state.mode="explicit demo";render()});
document.getElementById("importInternetTraining")?.addEventListener("click",async()=>{try{const data=await ISSFeeds.training();localStorage.setItem("issTrainingRows",JSON.stringify(data.rows||[]));document.getElementById("internetTrainingStatus").textContent=`Imported ${data.row_count||0} validated rows`}catch(e){document.getElementById("internetTrainingStatus").textContent=`Import failed: ${e.message}`}});
startup();
